// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeVy3rfUf4kg0YJy3-VExBE1hjvbYx9kw',
    appId: '1:742595730317:web:7b4953e967902017f5bbc4',
    messagingSenderId: '742595730317',
    projectId: 'registration-da6b5',
    authDomain: 'registration-da6b5.firebaseapp.com',
    storageBucket: 'registration-da6b5.firebasestorage.app',
    measurementId: 'G-SZESQH4GY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0rjdy4kgejgZeqwoq9LYe-Kv9MWNftsg',
    appId: '1:742595730317:android:ab42169f09707de1f5bbc4',
    messagingSenderId: '742595730317',
    projectId: 'registration-da6b5',
    storageBucket: 'registration-da6b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoBckp8h9rm05NrL5-hxSJBsaJUi-JFWs',
    appId: '1:742595730317:ios:83b07608eb701688f5bbc4',
    messagingSenderId: '742595730317',
    projectId: 'registration-da6b5',
    storageBucket: 'registration-da6b5.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoBckp8h9rm05NrL5-hxSJBsaJUi-JFWs',
    appId: '1:742595730317:ios:83b07608eb701688f5bbc4',
    messagingSenderId: '742595730317',
    projectId: 'registration-da6b5',
    storageBucket: 'registration-da6b5.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeVy3rfUf4kg0YJy3-VExBE1hjvbYx9kw',
    appId: '1:742595730317:web:772cd80935024489f5bbc4',
    messagingSenderId: '742595730317',
    projectId: 'registration-da6b5',
    authDomain: 'registration-da6b5.firebaseapp.com',
    storageBucket: 'registration-da6b5.firebasestorage.app',
    measurementId: 'G-T74P5WS6B8',
  );
}
